/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms_p1;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author falak
 */
public class HealthSupporter extends javax.swing.JFrame {

    /**
     * Creates new form HealthSupporter
     */
    public HealthSupporter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome = new javax.swing.JLabel();
        hsName = new javax.swing.JLabel();
        profile = new javax.swing.JButton();
        listOfPatients = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        becomePatient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcome.setText("Welcome!");

        profile.setText("Profile");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });

        listOfPatients.setText("List of Patients");
        listOfPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOfPatientsActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        becomePatient.setText("Become a Patient");
        becomePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                becomePatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(becomePatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listOfPatients, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(welcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hsName, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hsName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listOfPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(becomePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
        //TODO: extract info from people table and populate data on profile page
        this.setVisible(false);
        Profile profile = new Profile();
        profile.setVisible(true);
        String firstname = "";
        String lastName = "";
        String Dob = "";
        String Gender = "";

        String address = "";
        String Contact = "";
        String patientCategory = "";
        String diagnosis = "";
        String HS = "";
        try {
            Setup.rs = Setup.stmt.executeQuery("SELECT firstName, lastName, Dob, Gender, address, Phone FROM People where user_id = "
                    + "'" + Setup.loginuserid + "'");

            while (Setup.rs.next()) {
                firstname = Setup.rs.getString("firstName");
                lastName = Setup.rs.getString("lastName");
                Dob = Setup.rs.getString("Dob");
                Gender = Setup.rs.getString("Gender");
                Contact = Setup.rs.getString("Phone");
                address = Setup.rs.getString("address");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }

        profile.getName.setText(firstname);
        profile.getLastName.setText(lastName);
        profile.getDob.setText(Dob);
        profile.getGender.setText(Gender);
        profile.getContact.setText(Contact);
        profile.enterAddress.setText(address);
    }//GEN-LAST:event_profileActionPerformed

    private void listOfPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listOfPatientsActionPerformed
        try {
            HSListOfPatients patientlist = new HSListOfPatients();

            // TODO add your handling code here:
            Setup.rs = Setup.stmt.executeQuery("SELECT h.patient_id, p.Firstname, p.Lastname FROM "
                    + "Health_Supporter h, People p WHERE "
                    + "h.user_id='" + Setup.loginuserid + "' AND h.patient_id=p.user_id");

            patientlist.patientList.setModel(DbUtils.resultSetToTableModel(Setup.rs));
            this.setVisible(false);

            patientlist.setVisible(true);

        } catch (SQLException ex) {
            Logger.getLogger(HealthSupporter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listOfPatientsActionPerformed

    private void becomePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_becomePatientActionPerformed
        // TODO add your handling code here:
         try {
            
            // TODO add your handling code here:
            String query_update_people = "UPDATE People SET is_patient='Y' WHERE "
                    + "user_id = '" + Setup.loginuserid + "'";
             System.out.println(query_update_people);
            Setup.stmt.executeUpdate(query_update_people);

            this.setVisible(false);
            new HealthSupporter().setVisible(true);


        } catch (SQLException ex) {
            Logger.getLogger(HealthSupporter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_becomePatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HealthSupporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HealthSupporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HealthSupporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HealthSupporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HealthSupporter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton becomePatient;
    private javax.swing.JLabel hsName;
    private javax.swing.JButton listOfPatients;
    private javax.swing.JButton logout;
    private javax.swing.JButton profile;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
