/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms_p1;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author parinsanghavi
 */
public class PatientHealthSupporter extends javax.swing.JFrame {

    /**
     * Creates new form patientHealthSupporter
     */
    public PatientHealthSupporter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hsTable = new javax.swing.JTable();
        addID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delete.setText("DEL");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        hsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "UID", "NAME", "Contact", "Auth_date"
            }
        ));
        jScrollPane1.setViewportView(hsTable);

        addID.setText(" ");

        jLabel1.setText("Enter health supporter id");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(99, 99, 99)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(145, 145, 145)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(delete)
                                .addComponent(add))
                            .addGap(81, 81, 81)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete)
                    .addComponent(addID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String user_id = addID.getText().toString().replaceAll("\\s+", "");
        try {
            System.out.println(user_id + ";" + Setup.loginuserid);
            String dummy = "Insert into Health_Supporter values ('"
                    + user_id + "', Sysdate, '" + Setup.loginuserid + "')";
            System.out.println(dummy);
            Setup.stmt.executeUpdate(dummy);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        this.setVisible(false);
        Patient p = new Patient();
        p.setVisible(true);
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String user_id = addID.getText().toString().replaceAll("\\s+", "");
        String is_sick = "";
        String count_hs = "";
        try {

            String query = "SELECT is_sick FROM Patient WHERE user_id ='"
                    + Setup.loginuserid + "'";
            System.out.println(query);
            Setup.rs = Setup.stmt.executeQuery(query);
            while (Setup.rs.next()) {
                is_sick = Setup.rs.getString("is_sick");
            }
            System.out.println(is_sick);
            if (is_sick.equals("Y")) {
                String query_count = "SELECT COUNT(*) AS CountHS FROM Health_Supporter WHERE "
                        + "patient_id = '" + Setup.loginuserid + "'";
                Setup.rs = Setup.stmt.executeQuery(query_count);
                while (Setup.rs.next()) {
                    count_hs = Setup.rs.getString("CountHS");
                }
                System.out.println(count_hs);
                if (count_hs.equals("2")) {
                    String query_deleteHS = "DELETE FROM Health_Supporter WHERE "
                            + "user_id = '" + user_id + "' AND "
                            + "patient_id='" + Setup.loginuserid + "'";
                    String updateSP = "UPDATE Sick_patient SET hsid1 = null WHERE "
                            + "user_id = '" + Setup.loginuserid + " AND "
                            + "hsid1 = '" + user_id + "'";
                    String updateSP2 = "UPDATE Sick_patient SET hsid2 = null WHERE "
                            + "user_id = '" + Setup.loginuserid + " AND "
                            + "hsid2 = '" + user_id + "'";

                    Setup.stmt.executeUpdate(query_deleteHS);
                    Setup.stmt.executeUpdate(updateSP);
                    Setup.stmt.executeUpdate(updateSP2);
                } else {
                    JOptionPane.showMessageDialog(null, "Cannot delete just one Health Supporter");
                }
            } else if (is_sick.equals("N")) {
                String query_deleteHs = "DELETE FROM Health_Supporter WHERE "
                        + "user_id='" + user_id + "' AND "
                        + "patient_id = '" + Setup.loginuserid + "'";
                String updateWP = "UPDATE Well_patient SET hsid1 = null WHERE "
                        + "user_id = '" + Setup.loginuserid + " AND "
                        + "hsid1 = '" + user_id + "'";
                String updateWP2 = "UPDATE Well_patient SET hsid2 = null WHERE "
                        + "user_id = '" + Setup.loginuserid + " AND "
                        + "hsid2 = '" + user_id + "'";

                Setup.stmt.executeUpdate(query_deleteHs);
                Setup.stmt.executeUpdate(updateWP);
                Setup.stmt.executeUpdate(updateWP2);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        this.setVisible(false);
        Patient p = new Patient();
        p.setVisible(true);
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Patient p = new Patient();
        p.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientHealthSupporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientHealthSupporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientHealthSupporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientHealthSupporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //addHSNamereate and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientHealthSupporter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add;
    public javax.swing.JTextField addID;
    public javax.swing.JButton delete;
    public javax.swing.JTable hsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
